blog/urls.py
from django.conf.urls import url
from blog.views import * # 이렇게 수정하면 아래와 같이 views.~ 형식에서 views. 부분을 빼야 함
                         # bookmark.urls에서는 from . import views로 했으므로 views.~ 형식으로 사용해야 함
#  아래에서 blog/ 부분은 이미 처리되고 넘어온 상황임
urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # # Example: /2012/11/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),

    # # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # # Example: /2012/11/10/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # /blog/tag/ URL 요청을 처리할 뷰 클래스 지정, 태그 클라우드 출력용 뷰
    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # /blog/tag/태그 이름/ 요청을 처리할 뷰 클래스 지정
    # r'...': 이스케이프되지 않는 raw 스트링임을 표시
    # [^/]+ : / 이외 문자가 한번 이상 반복
    # (?u)  : 앞의 표현식을 유니코드로 인식하라고 지정(주소창에 한글 입력 가능하도록)
    # Example: /tag/tagname
     url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/  # ch09 1/1
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]
# 위에서 지정한 name 항목을 템플릿에서 사용할 때에는 이름공간을 포함하여,
# blog:index, blog:post_list, blog:post_detail, blog:post_archive, ... 로 명시해야 함

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from mysite.views import HomeView  # 추가!!!

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view(), name='home'),  # 추가!!!
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
# 문자열 처리 방식이 상이한 파이썬 버전 2 및 3의 호환성을 위한 임포트
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from tagging.fields import TagField                 # ch07 추가
from django.db import models
# url 패턴을 만들어주는 장고 내장 함수 reverse()를 위한 임포트
from django.core.urlresolvers import reverse

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    # 아래에서 관리자 화면의 레이블과 도움말은 모두 한글로 수정하였음(교과서에서는 대문자 영문이었음)
    # 한 줄로 입력되는 CharField
    title = models.CharField('제목', max_length=50)
    slug = models.SlugField('슬러그',  # 기본 길이 50, 인덱스가 기본 생성됨,
                                       # 제목에서 주요 단어를 하으픈으로 연결하여 생성
                            unique=True,  # unique 설정, 기본키 대용으로 사용 가능
                            allow_unicode=True,  # 한글 입력 가능하도록
                            help_text='제목에 대한 한 단어의 별명.')
    description = models.CharField('설명',
                                   max_length=100,
                                   blank=True,  # 블랭크 허용
                                   help_text='간략한 설명 문구.')
    content = models.TextField('내용')  # TextField이므로 여러 줄 입력 가능함
    create_date = models.DateTimeField('최초 생성 일시',
                                       auto_now_add=True)  # 최초 생성 일시를 자동 저장하도록
    modify_date = models.DateTimeField('최종 수정 일시',
                                       auto_now=True)  # 최종 수정 일시를 자동 저장하도록
    tag = TagField('태그',  # ch07 추가
                   help_text='게시글에 대한 태그')  # ch07 추가

    class Meta:  # 필드 속성 외에 필요한 파라미터를 Meta 내부 클래스로 정의
        verbose_name = '기사'              # 'post'
        verbose_name_plural = '기사 모음'  # 'posts'
        db_table  = 'my_posts'           # DB에 저장할 테이블 이름을 my_posts'라고 지정
                                         # 기본값(앱이름_모델클래스이름)은 'blog_post'
        ordering  = ('-modify_date',)  # 최종 수정 일시의 내림차순 정렬

    def __str__(self):
        return self.title  # 객체를 출력할 때 제목만 출력

    def get_absolute_url(self): # 이 메소드가 정의된 객체를 지칭하는 URL을 반환
        # 아래에서 'blog:post_detail'는 blog 앱 이름공간의 post_detail이란 의미
        # # Example: /post/django-example/
        # url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
        return reverse('blog:post_detail', args=(self.slug,))
    def get_previous_post(self):  # 3.2.5 항에서 템플릿 작성할 때 사용
        return self.get_previous_by_modify_date()

    def get_next_post(self):  # 3.2.5 항에서 템플릿 작성할 때 사용
        return self.get_next_by_modify_date()

blog/forms.py
# ch09 1/1 추가 시작
# 장고에서는 폼도 클래스를 활용하여 정의
from django import forms

# django.forms.Form 클래스를 상속받아 폼을 작성
class PostSearchForm(forms.Form):
    # 폼을 정의하는 방법은 테이블의 모델 클래스를 정의하는 방법과 유사함
    # CharField는 TextInput 위젯으로 표현됨
    # TextInput 위젯 앞에 label이 표시되고,
    # 변수 search_word는 입력 필드에 대한 id 역할
    search_word = forms.CharField(label='검색어')
# ch09 1/1 추가 종료

blog/views.py
# 뷰 작성에 필요한 클래스형 제넥릭 뷰 임포트
from django.views.generic import ListView, DetailView,TemplateView
# 뷰 작성에 필요한 날짜 제네릭 뷰 임포트
from django.views.generic.dates import ArchiveIndexView, \
    YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView
# blog.models.Post 클래스 임포트
from blog.models import Post
from tagging.models import Tag, TaggedItem                          # ch07추가02
from tagging.views import TaggedObjectList                          # ch07추가03

# 아래 두 클래스 추가                                               # ch07추가04
# /blog/tag/ 요청에 따라 태그 클라우드 템플릿을 출력
# TemplateView 제네릭 뷰는 테이블 처리 없이 단순 템플릿 렌더링 처리만 담당하는 뷰
class TagTV(TemplateView) :
    template_name = 'tagging/tagging_cloud.html' # 태그 클라우드를 출력하는 템플릿

# TaggedObjectList는 ListView를 상속받는 뷰로서,
# tagging 패키지는 tagging 패키지의 views.py에 정의되어 있는데,
# 모델과 태그가 지정되면, 해당 태그가 지정된 모델의 객체 리스트를
# 지정된 템플릿에 전달하는 역할
class PostTOL(TaggedObjectList) :
    model = Post
    template_name = 'tagging/tagging_post_list.html'

# ListView를 상속받아서 PostLV 작성
class PostLV(ListView) :
    model = Post
    # 기본값 'blog/post_list.html' 대신 지정 (3.1.4 URL 설계 항 참고)
    template_name = 'blog/post_all.html'
    # 컨텍스트 객체 이름을 기본값(object_list)와 다르게 지정했지만,
    # 기본값(object_list)도 여전히 사용 가능함
    context_object_name = 'posts'
    paginate_by = 5  # 페이지 당 5 개 객체를 처리하도록 지정

# DetailView를 상속받아서 PostDV 작성
# 기본키 대신 slug를 전달 받고, 나머지 속성은 기본값 사용
# slug는 URLconf가 전달해줌(3.1.4 URL 설계 항 참고)
class PostDV(DetailView) :
    model = Post

# 모든 아카이브 클래스에서 기준 날짜(date_filed) 속성을 modify_date로 지정

# ArchiveIndexView를 상속받아서 PostAV 작성
class PostAV(ArchiveIndexView) :
    model = Post
    date_field = 'modify_date'

# YearArchiveView를 상속받아서 PostYAV 작성
class PostYAV(YearArchiveView) :
    model = Post
    date_field = 'modify_date'
    make_object_list = True    # 기본값은 False이지만,
    # object_list 컨텍스트 변수를 생성해서 템플릿에 전달하도록 지시
    # URLconf에서 추출한 연도 값을 전달받아서 object_list를 구성하고
    # 이를 템플릿에 전달함

# MonthArchiveView를 상속받아서 PostMAV 작성
class PostMAV(MonthArchiveView) :
    model = Post
    date_field = 'modify_date'
    # URLconf에서 추출한 연도 및 월 값을 전달받아서 object_list를 구성하고
    # 이를 템플릿에 전달함

# DayArchiveView를 상속받아서 PostDAV 작성
class PostDAV(DayArchiveView) :
    model = Post
    date_field = 'modify_date'
    # URLconf에서 추출한 연도, 월, 일 값을 전달받아서 object_list를 구성하고
    # 이를 템플릿에 전달함

# TodayArchiveView를 상속받아서 PostTAV 작성
class PostTAV(TodayArchiveView) :
    model = Post
    date_field = 'modify_date'
    # URLconf에서 지정한 당일(today)에 해당하는 object_list를 구성하고
    # 이를 템플릿에 전달함

# ch09추가 1/1 시작
from django.views.generic.edit import FormView
from blog.forms import PostSearchForm
from django.db.models import Q                  # 검색 기능에 필요한 클래스
from django.shortcuts import render             # 단축 함수 render()

# FormView를 상속받아 SearchFormView 작성
# FormView는 GET 요청인 경우 폼을 화면에 보여주고 사용자 입력을 대기함
# 사용자가 폼에 데이터 입력 후 제출하면 이는 POST 요청으로 접수되고
# 입력 데이터에 대한 유효성 검사를 실시하여 유효하면
# form_valid() 함수를 실행한 후 적절한 URL로 리다이렉트 처리함
class SearchFormView(FormView):
    form_class = PostSearchForm             # 폼으로 사용할 클래스를 지정
    template_name = 'blog/post_search.html' # 템플릿 지정

    # 입력 데이터에 대한 유효성 검사를 실시하여 유효하면 실행될 함수
    def form_valid(self, form) :
	    # POST 요청의 id가 'search_word'인 값을 추출하여 변수에 저장
        schWord = '%s' % self.request.POST['search_word']
	    # filter() 메소드의 매칭 조건을 Q 객체로 다양하게 지정 가능함
	    # 각 조건에서 icontains 연산자는 대소문자 구별 없이
	    # 검색어가 포함되었는지 검사
	    # distinct() 메소드는 중복된 객체를 제외함
	    # 결국, Post 테이블의 모든 레코드에 대하여
	    # title, description, content, tag 필드에
	    # schWord가 포함된 레코드를 대소문자 구별 없이 검색해서 중복 없는 리스트로 저장
        post_list = Post.objects.filter(
	        Q(title__icontains=schWord) |
	        Q(description__icontains=schWord) |
	        Q(content__icontains=schWord) |
	        Q(tag__icontains=schWord)
        ).distinct()

        # 템플릿에 전달할 맥락 변수 context를 사전 형식으로 정의
        context = {}
        context['form'] = form  # 여기서 form은 PostSearchForm을 지칭함
        context['search_term'] = schWord
        context['object_list'] = post_list

		# 단축 함수 render()는 템플릿과 맥락 변수를 처리하여,
	    # 최종적으로 HttpResponse 객체를 반환
	    # 일반적으로 form_valid() 함수는 리다이렉트 처리를 위하여
	    # HttpResponseRedirect 객체를 반환하는데,
	    # 여기서는 render() 함수가 HttpResponse 객체를 반환하므로
	    # 리다이렉트 처리가 되지 않게됨.
        return render(self.request, self.template_name, context)
# ch09 추가 1/1 종료

blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% block title %}장고 게시판 목록{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/tabular.css" %}{% endblock %}
{% block content %}
    <div id="content">
        <h1 class="centered">블로그 목록 (표 형식)</h1>
        <table id="tbl" >
            <tr>
                <th>번호</th>
                <th>최종 수정일</th>
                <th>제목</th>
                <th>슬러그</th>
                <th>요약</th>
            </tr>
            {% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.modify_date|date:"Y년 m월 d일" }}</td>
                <td><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></td>
                <td>{{ post.slug }}</td>
                <td>{{ post.description }}</td>
            </tr>
            {% endfor %}
        </table>
        <br/>
        <!--이전/현재/다음 페이지 이동 -->
        <div class="centered"> <!--div 요소는 블록 요소-->
            <span>  <!--span 요소는 인라인 요소-->
                <!--page_obj는 장고 Page 객체가 들어있는 컨텍스트 변수이며
                has_previous, has_next, previous_page_number, next_page_number,
                number, pagenator.num_pages 속성을 가짐-->
                {% if page_obj.has_previous %}
                    <!--링크 형식 ?page=1에 주목-->
                    <a href="?page={{ page_obj.previous_page_number }}">이전 페이지</a>
                {% else  %}
                    첫 페이지  &nbsp;
                {% endif %}
                &nbsp;&nbsp;(
                {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                )&nbsp;&nbsp;

                {% if page_obj.has_next %} &nbsp;
                    <!--링크 형식 ?page=3에 주목-->
                    <a href="?page={{ page_obj.next_page_number }}">다음 페이지</a>
                {% else  %} &nbsp;
                    끝 페이지
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}
{% block title %}장고 게시글 저장소{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/tabular.css" %}{% endblock %}
{% block content %}
    <!--div#content 내부로 전체 콘텐츠 이동-->
    <div id="content">
        <h1 class="centered">{% now "Y년 m월 d일" %}까지 게시글 모음</h1>
        <ul class="centered">
            {% for date in date_list %}
                <li style="display: inline;">
                    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                        {{ date|date:"Y" }}년
                    </a>
                </li>&nbsp;&nbsp;
            {% endfor %}
        </ul>
        <br/>
        <div class="leftpadding30percent">
            <ul>
                {% for post in object_list %}
                    <li>
                        {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}">
                            <strong>{{ post.title }}</strong>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}
{% block title %}장고 게시글 저장소{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/tabular.css" %}{% endblock %}
{% block content %}
    <div id="content">
        <h1 class="centered">{{ day|date:"Y년 m월 d일"}} 게시글 모음</h1>
        <div class="leftpadding30percent">
            <ul>
                {% for post in object_list %}
                <li>
                    {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}
{% block title %}장고 게시글 저장소{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/tabular.css" %}{% endblock %}
{% block content %}
    <div id = "content">
        <h1 class="centered">{{ month|date:"Y년 m월" }} 게시글 모음</h1>

        <div class="leftpadding30percent">
            <ul>
                {% for post in object_list %}
                <li>
                    {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}
{% block title %}장고 게시글 목록{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/tabular.css" %}{% endblock %}
{% block content %}
    <!--div#content 내부로 전체 콘텐츠 이동-->
    <div id="content">
        <h1 class="centered">{{ year|date:"Y" }}년 게시글 모음</h1>
        <ul class="centered">
            {% for date in date_list %}
            <li style="display: inline">
                <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">
                    <!--월 제목을 "F" 형태(예: July)로 출력 -->
                    <!--{{ date|date:"F" }}-->
                    {{ date|date:"m" }}월
                </a>
                &nbsp; &nbsp;
            </li>
            {% endfor %}
        </ul>
        <br/>
        <div class="leftpadding30percent">
            <ul>
                {% for post in object_list %}
                <li>
                    {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% block title %}장고 게시글 보기{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/tabular.css" %}{% endblock %}
{% block content %}
    <!--div#content 내부로 전체 콘텐츠 이동-->
    <div id="content" class="centered">

        <p class="other_posts">
            {% if object.get_previous_by_modify_date %}
                <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">
                    &laquo;-- {{ object.get_previous_post }}
                </a>
            {% endif %}

            {% if object.get_next_by_modify_date %}
                &nbsp; |
                <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">
                    {{ object.get_next_post }} --&raquo;
                </a>
            {% endif %}
        </p>

    <table id="tbl" >
            <tr>
                <th>구분</th>
                <th>내용</th>
            </tr>
           <tr>
                <td>제목</td>
                <td> <h2>{{ object.title }}</h2></td>
            </tr>
            <tr>
                <td>슬러그</td>
                <td>{{ object.slug}}</td>
            </tr>
            <tr>
                <td>한 줄 요약</td>
                <td>{{ object.description}}</td>
            </tr>
            <tr>
                <td>내용</td>
                <td>{{ object.content|linebreaks }}</td>
            </tr>

            <tr>
                <td>최초 등록 일시</td>
                <td>{{ object.create_date|date:"Y년 m월 d일" }}</td>
            </tr>
            <tr>
                <td>최근 수정 일시</td>
                <td>{{ object.modify_date|date:"Y년 m월 d일" }}</td>
            </tr>
            <!--tagging 패키지에 정의된 커스텀 태그 사용을 위해 tagging_tags 모듈을 적재-->
            <!--ch07 추가-->
            {% load tagging_tags %}
            <!--tags_for_object 커스텀 태그를 사용하여 object 객체에 지정된 태그 리스트를 추출하여-->
            <!--tags 템플릿 변수에 저장, 여기서 object 객체는 PostDV 뷰에서 전달받는 컨텍스트 변수로서,-->
            <!--특정 Post 객체가 저장되어 있음-->
            {% tags_for_object object as tags %}
            <tr> <!--게시글마다 지정된 태그를 출력-->
                <td>태그</td>
                <td>
                    {% for tag in tags %}
                        <a href="{% url 'blog:tagged_object_list' tag.name %}">
                          {{tag.name}}&nbsp;&nbsp;
                        </a>
                    {% endfor %}
                </td>
            </tr>
            <tr> <!--게시판에 지정된 태그 클라우드를 출력-->
                <td>태그 클라우드</td>
                <td>
                    <!--http://localhost:8000/blog/tag/-->
                    <!--embed 태그를 활용해서 src에 지정된 템플릿을 해당 영역에 출력-->
                    <embed type="text/html" src="{% url 'blog:tag_cloud' %}">
                </td>
            </tr>
        </table>
       <br/>                           <!-- ch08 1/5  -->
        <div>                           <!-- ch08 2/5  -->
            {% load disqus_tags %}      <!-- ch08 3/5  -->
             {% disqus_show_comments %}  <!-- ch08 4/5  -->
         </div>                          <!-- ch08 5/5  -->
    </div>
{% endblock %}}

blog/templates/blog/post_search.html
<!--ch09 작성 시작-->
{% extends "base.html" %}
{% block title %}장고 게시글 검색{% endblock %}
{% load staticfiles %}
{% block extrastyle %}{% static "css/tabular.css" %}{% endblock %}
{% block content %}
<div id="content">
    <!--blog.views.SearchFormView.form_valid() 함수와 함께 보면서 작업하라-->
    <h1 class="centered">게시글 검색</h1>
    <!--form 태그로 폼을 출력, 확인 누르면 POST 방식으로 요청을 동일한 URL로 전송-->
    <!--CSRF 공격(Cross Site Request Forgery) 출처: http://itstory.tk/entry/CSRF-공격이란-그리고-CSRF-방어-방법 [덕's IT Story]-->
    <!--csrf-token 태그를 써서 CSRF 공격을 방지-->
    <form action="." method="post" class="centered"> {% csrf_token %}
        <!--form은 뷰가 넘겨준 PostSearchForm을 의미함-->
        {{ form.as_table }}
        <input type="submit" value="확인" />
    </form>
    <br/><br/>
    {% if object_list and search_term %}
        <h2 class="centered">({{ search_term }})에 대한 검색  결과</h2>
        <table id="tbl">
            <tr>
                <th>번호</th>
                <th>최종 수정일</th>
                <th>제목</th>
                <th>슬러그</th>
                <th>요약</th>
                <th>태그</th>
            </tr>
            {% for post in object_list %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.modify_date|date:"Y년 m월 d일" }}</td>
                <td>
                    <a href='{{ post.get_absolute_url }}'>
                        <strong>{{ post.title }}</strong>
                    </a>
                </td>
                <td>{{ post.slug }}</td>
                <td>{{ post.description }}</td>
                <td>{{ post.tag }}</td>
            </tr>
            {% endfor %}
        </table>
    {% elif search_term %}
        <p class="centered">
            <strong><i>
                ({{ search_term }})에 대한 검색 결과가 없습니다!
            </i></strong>
        </p>
    {% endif %}
</div>
{% endblock %}
<!--ch09 작성 종료-->