blog/urls.py
from django.conf.urls import url
from blog.views import * # 이렇게 수정하면 아래와 같이 views.~ 형식에서 views. 부분을 빼야 함
                         # bookmark.urls에서는 from . import views로 했으므로 views.~ 형식으로 사용해야 함
#  아래에서 blog/ 부분은 이미 처리되고 넘어온 상황임
urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # # Example: /2012/11/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),

    # # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # # Example: /2012/11/10/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    # /blog/tag/ URL 요청을 처리할 뷰 클래스 지정, 태그 클라우드 출력용 뷰
    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # /blog/tag/태그 이름/ 요청을 처리할 뷰 클래스 지정
    # r'...': 이스케이프되지 않는 raw 스트링임을 표시
    # [^/]+ : / 이외 문자가 한번 이상 반복
    # (?u)  : 앞의 표현식을 유니코드로 인식하라고 지정(주소창에 한글 입력 가능하도록)
    # Example: /tag/tagname
     url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/  # ch09 1/1
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]
# 위에서 지정한 name 항목을 템플릿에서 사용할 때에는 이름공간을 포함하여,
# blog:index, blog:post_list, blog:post_detail, blog:post_archive, ... 로 명시해야 함

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from mysite.views import HomeView  # 추가!!!

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomeView.as_view(), name='home'),  # 추가!!!
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

templates/base.html
<!DOCTYPE html>     <!--HTML5 규약을 준수하는 파일-->
<html lang="ko">    <!--언어는 한국어로 지정--><!---->

<head>              <!--페이지 타이틀과 css 파일 2개를 연결-->
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}  <!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
<!--스타일시트 css/base.css 작성이 필요함-->
<link href="https://fonts.googleapis.com/css?family=Poor+Story" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>              <!--바디 영역은 4 영역(헤더/메뉴/콘텐츠/풋터)으로 구성-->

<div id="header">                   <!--헤더 영역-->
    <h2 class="maintitle">쉽고 빠른 장고 웹 프로그래밍</h2>
    <h4 class="welcome">반갑습니다. <a href="#">한 은경</a>님.  /
                <a href="#">비밀번호 변경</a> /
                <a href="#">로그아웃</a>
    </h4>
</div>

<div id="menu">                     <!--메뉴 영역-->
    <li><a href="{% url 'home' %}">홈</a></li>
    <li><a href="{% url 'bookmark:index' %}">책갈피</a></li>
    <li><a href="{% url 'blog:index' %}">게시판</a></li>
    <li><a href="#">사진첩</a></li>

    <li><a href="#">추가&bigtriangledown;</a>             <!--드롭다운 메뉴 구성-->
        <ul>
            <li><a href="#">책갈피</a></li>
            <li><a href="#">게시판</a></li>
	        <li><a href="#">사진첩</a></li>
        </ul>
    </li>
    <li><a href="#">편집&bigtriangledown;</a>             <!--드롭다운 메뉴 구성-->
        <ul>
            <li><a href="#">책갈피</a></li>
            <li><a href="#">게시판</a></li>
	        <li><a href="#">사진첩</a></li>
        </ul>
    </li>

    <li><a href="{% url 'blog:post_archive' %}">저장소</a></li>
     <li><a href="{% url 'blog:search' %}">검색</a></li>     <!--ch09 수정 1/1-->
    <li><a href="{% url 'admin:index' %}">관리자</a></li>
</div>

{% block content %}{% endblock %}   <!--블록 태그로 콘텐츠 영역 정의 -->

{% block footer %}{% endblock %}    <!--블록 태그로 풋터 영역 정의-->

</body>
</html>

templates/home.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}장고 웹 사이트{% endblock %}    <!--title 블록 재정의-->

<!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
{% load staticfiles %}
<!--extrastyle 블록을 재정의하여 추가적으로 home.css 연결-->
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}                         <!--content 블록 재정의-->

<div id="content_home">     <!--content_home 영역 정의-->

    <div id="homeimg">      <!--homeimg 영역 정의-->
        <!--<a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>-->
        <a href="/"><img src="{% static 'img/python_django.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">장고 프레임워크로 개발한 웹 사이트입니다.</h4>
    </div>

    <hr style="margin: 5px 0;">     <!--그림 및으로 5px 간격을 두고 수평선 넣기-->

    <h2>웹 앱 선택</h2>

    <table id="applist">
        <tr>
        <td><b><i><a href="{% url 'bookmark:index' %}">책갈피</a></i><b></td>
        <td>당신의 책갈피를 등록하고 다른 사람들과 공유할 수 있습니다. 어쩌구 저쩌구. 중얼중얼.</td>
        <td id="Edit"><i><a href="#">등록</a></i></td>
        <td id="Edit"><i><a href="#">편집</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'blog:index' %}">게시판</a></i><b></td>
        <td>당신의 게시물을 등록하고 다른 사람들과 공유할 수 있습니다. 어쩌구 저쩌구.</td>
        <td id="Edit"><i><a href="#">등록</a></i></td>
        <td id="Edit"><i><a href="#">편집</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="#">사진첩</a></i><b></td>
        <td>당신의 사진을 등록하고 다른 사람들과 공유할 수 있습니다. 어쩌구 저쩌구.</td>
        <td id="Edit"><i><a href="#">등록</a></i></td>
        <td id="Edit"><i><a href="#">편집</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}                      <!--footer 블록 재정의-->
<div id="footer">
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Copyleft.svg/220px-Copyleft.svg.png"
         height="12" width="12" /> eunkyung 2018
</div>
{% endblock footer %}

templates/hometest.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}home.html{% endblock %}    <!--title 블록 재정의-->

{% block content %}                         <!--content 블록 재정의-->
    <div id="content">
        This is CONTENT area.
    </div>
{% endblock content %}

{% block footer %}                          <!--footer 블록 재정의-->
    <div id="footer">
        This is FOOTER area.
    </div>
{% endblock footer %}